### ISSUE TITLE
Doc Recommendation: Quick Start Guide

### ISSUE THREAD

**Issue by zombieCraig** [db0/godot-card-gaming#102]
It would be helpful having the INSTALL broken down into a quick start guide and an advanced configuration guide.  The quickstart could be something like create your own custom Yellow card and having it show up in the demo deck.  That would teach most of the initial core concepts and give them a taste for how the Objects interact.  Then they could use the advanced configuration portion to build out further.

**Comment by db0** [comment]
Good idea! Thanks

**Comment by db0** [comment]
[Done!](https://github.com/db0/godot-card-gaming/blob/main/tutorial/QUICKSTART.md)
