### ISSUE TITLE
1.3 Trying to assign value of type 'MarginContainer' to variable of type 'CardFront.gd'

### ISSUE THREAD

**Issue by zombieCraig** [db0/godot-card-gaming#115]
CardTemplate.gd:198
`card_front = $Control/Front.get_child(0)`

To recreate:
* Draw card off of deck to hand
* Highlight card in Hand by hovering over it with a mouse

**Comment by db0** [comment]
Is this about the current grid-based-placement branch, or the main?

**Comment by zombieCraig** [comment]
Main

**Comment by db0** [comment]
I can't replicate this.

**Comment by db0** [comment]
Is this still happening? I've never encountered this.

**Comment by zombieCraig** [comment]
If you are not getting it, it maybe an artifact from merging my forked
branch.  We can close for now until I can dig it further.
