### ISSUE TITLE
Attempting to press hover buttons sometimes results in dragging card instead

### ISSUE THREAD

**Issue by BubblineBee** [db0/godot-card-gaming#68]
When pressing the hover buttons if the mouse click is held for too long (more than just a quick tap) instead of the hover button performing its action the card is dragged instead. This makes it very difficult to actually use the hover buttons.

**Comment by db0** [comment]
Mmm, yes I've noticed that too sometimes. I will extend the time required to start dragging the card. Unfortunately a lot of this behaviour is caused by me trying to work around godotengine/godot#16854

**Comment by db0** [comment]
Fix caused more problems than it solved. Had to revert it.
