### ISSUE TITLE
Adjust title and card text font size depending on the amount of chars

### ISSUE THREAD

**Issue by db0** [db0/godot-card-gaming#70]
If one puts too much text in the card, it exceeds its panel boundaries. Font size should start decreasing when there's too many chars, so that it always fits in the rect.

**Comment by vmjcv** [comment]
i will do it

**Comment by vmjcv** [comment]
you can see this 
https://github.com/db0/godot-card-gaming/pull/73

**Comment by db0** [comment]
Thanks. Just FYI, if you put the number of the Issue (like "#70") into your commit or pull request, it will update the issue as well. This way you don't have to manually leave a comment in the issue
